### PR TITLE
Check inner payload length in SignedPayload::from_payload to avoid overflow

### LINKED ISSUE #58: u32 overflow in SignedPayload::from_payload
### What version are you using?

Most up-to-date codebase

### What did you do?

Called `stellar_strkey::ed25519::SignedPayload::from_payload` with following payload:
```rust
let payload: Vec<u8> = vec![
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    ];
```

### What did you expect to see?

Program exit with error `DecodeError::Invalid`

### What did you see instead?

Program panics:
```
thread 'test_signed_payload_from_payload' panicked at src/ed25519.rs:262:12:
attempt to add with overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:117:5
   3: stellar_strkey::ed25519::SignedPayload::from_payload
             at ./src/ed25519.rs:262:12
   4: tests::test_signed_payload_from_payload
             at ./tests/tests.rs:249:16
   5: tests::test_signed_payload_from_payload::{{closure}}
             at ./tests/tests.rs:243:39
   6: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
```

This is because of the following line:
```rust
inner_payload_len + (4 - inner_payload_len % 4) % 4
```
`inner_payload_len` is `0xffffffff` so `(4 - inner_payload_len % 4) % 4 = 1` so
```rust
inner_payload_len + (4 - inner_payload_len % 4) % 4 = u32::MAX + 1
```
which overflow.

### PR DESCRIPTION
**Pull request by C0x41lch0x41**
### What

In SignedPayload::from_payload check inner payload length extracted from the payload to avoid a u32 overflow

### Why

See #58

Closes #58

### CODE REVIEW

File: src/ed25519.rs [hunk 1]
```diff
@@ -259,6 +260,9 @@ impl SignedPayload {
                 .try_into()
                 .map_err(|_| DecodeError::Invalid)?,
         );
+        if inner_payload_len > MAX_INNER_PAYLOAD_LENGTH {
```
Comment (leighmcculloch) [inline src/ed25519.rs:263]: @C0x41lch0x41 I pushed a tweak in a2495af that has the len check here be against `64`, because actually the fn isn't supposed to support inner payloads greater than that length. At the top of the fn the entire payload is checked to fit inside a total length that requires the inner payload to be no longer than 64 bytes long.

**Review by leighmcculloch — APPROVED** [review]

File: src/ed25519.rs (hunk 1 above)
Comment (C0x41lch0x41) [reply src/ed25519.rs:263]: Yes that looks good to me thanks @leighmcculloch
